# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Recordings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recordings
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources', '~> 4.0'

  target 'RecordingsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
